# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.26.3/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.26.3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/gregg/code/Perseus

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/gregg/code/Perseus

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.26.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.26.3/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/gregg/code/Perseus/CMakeFiles /Users/gregg/code/Perseus//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/gregg/code/Perseus/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named perseus

# Build rule for target.
perseus: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 perseus
.PHONY : perseus

# fast build rule for target.
perseus/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/perseus.dir/build.make CMakeFiles/perseus.dir/build
.PHONY : perseus/fast

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/build
.PHONY : tests/fast

src/geometry.o: src/geometry.cpp.o
.PHONY : src/geometry.o

# target to build an object file
src/geometry.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/perseus.dir/build.make CMakeFiles/perseus.dir/src/geometry.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/geometry.cpp.o
.PHONY : src/geometry.cpp.o

src/geometry.i: src/geometry.cpp.i
.PHONY : src/geometry.i

# target to preprocess a source file
src/geometry.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/perseus.dir/build.make CMakeFiles/perseus.dir/src/geometry.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/geometry.cpp.i
.PHONY : src/geometry.cpp.i

src/geometry.s: src/geometry.cpp.s
.PHONY : src/geometry.s

# target to generate assembly for a file
src/geometry.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/perseus.dir/build.make CMakeFiles/perseus.dir/src/geometry.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/geometry.cpp.s
.PHONY : src/geometry.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/perseus.dir/build.make CMakeFiles/perseus.dir/src/main.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/perseus.dir/build.make CMakeFiles/perseus.dir/src/main.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/perseus.dir/build.make CMakeFiles/perseus.dir/src/main.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/move.o: src/move.cpp.o
.PHONY : src/move.o

# target to build an object file
src/move.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/perseus.dir/build.make CMakeFiles/perseus.dir/src/move.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/move.cpp.o
.PHONY : src/move.cpp.o

src/move.i: src/move.cpp.i
.PHONY : src/move.i

# target to preprocess a source file
src/move.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/perseus.dir/build.make CMakeFiles/perseus.dir/src/move.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/move.cpp.i
.PHONY : src/move.cpp.i

src/move.s: src/move.cpp.s
.PHONY : src/move.s

# target to generate assembly for a file
src/move.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/perseus.dir/build.make CMakeFiles/perseus.dir/src/move.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/move.cpp.s
.PHONY : src/move.cpp.s

src/move_generation.o: src/move_generation.cpp.o
.PHONY : src/move_generation.o

# target to build an object file
src/move_generation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/perseus.dir/build.make CMakeFiles/perseus.dir/src/move_generation.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/move_generation.cpp.o
.PHONY : src/move_generation.cpp.o

src/move_generation.i: src/move_generation.cpp.i
.PHONY : src/move_generation.i

# target to preprocess a source file
src/move_generation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/perseus.dir/build.make CMakeFiles/perseus.dir/src/move_generation.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/move_generation.cpp.i
.PHONY : src/move_generation.cpp.i

src/move_generation.s: src/move_generation.cpp.s
.PHONY : src/move_generation.s

# target to generate assembly for a file
src/move_generation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/perseus.dir/build.make CMakeFiles/perseus.dir/src/move_generation.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/move_generation.cpp.s
.PHONY : src/move_generation.cpp.s

src/network.o: src/network.cpp.o
.PHONY : src/network.o

# target to build an object file
src/network.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/perseus.dir/build.make CMakeFiles/perseus.dir/src/network.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/network.cpp.o
.PHONY : src/network.cpp.o

src/network.i: src/network.cpp.i
.PHONY : src/network.i

# target to preprocess a source file
src/network.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/perseus.dir/build.make CMakeFiles/perseus.dir/src/network.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/network.cpp.i
.PHONY : src/network.cpp.i

src/network.s: src/network.cpp.s
.PHONY : src/network.s

# target to generate assembly for a file
src/network.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/perseus.dir/build.make CMakeFiles/perseus.dir/src/network.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/network.cpp.s
.PHONY : src/network.cpp.s

src/square.o: src/square.cpp.o
.PHONY : src/square.o

# target to build an object file
src/square.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/perseus.dir/build.make CMakeFiles/perseus.dir/src/square.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/square.cpp.o
.PHONY : src/square.cpp.o

src/square.i: src/square.cpp.i
.PHONY : src/square.i

# target to preprocess a source file
src/square.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/perseus.dir/build.make CMakeFiles/perseus.dir/src/square.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/square.cpp.i
.PHONY : src/square.cpp.i

src/square.s: src/square.cpp.s
.PHONY : src/square.s

# target to generate assembly for a file
src/square.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/perseus.dir/build.make CMakeFiles/perseus.dir/src/square.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/square.cpp.s
.PHONY : src/square.cpp.s

src/state.o: src/state.cpp.o
.PHONY : src/state.o

# target to build an object file
src/state.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/perseus.dir/build.make CMakeFiles/perseus.dir/src/state.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/state.cpp.o
.PHONY : src/state.cpp.o

src/state.i: src/state.cpp.i
.PHONY : src/state.i

# target to preprocess a source file
src/state.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/perseus.dir/build.make CMakeFiles/perseus.dir/src/state.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/state.cpp.i
.PHONY : src/state.cpp.i

src/state.s: src/state.cpp.s
.PHONY : src/state.s

# target to generate assembly for a file
src/state.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/perseus.dir/build.make CMakeFiles/perseus.dir/src/state.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/state.cpp.s
.PHONY : src/state.cpp.s

src/string_transforms.o: src/string_transforms.cpp.o
.PHONY : src/string_transforms.o

# target to build an object file
src/string_transforms.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/perseus.dir/build.make CMakeFiles/perseus.dir/src/string_transforms.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/string_transforms.cpp.o
.PHONY : src/string_transforms.cpp.o

src/string_transforms.i: src/string_transforms.cpp.i
.PHONY : src/string_transforms.i

# target to preprocess a source file
src/string_transforms.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/perseus.dir/build.make CMakeFiles/perseus.dir/src/string_transforms.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/string_transforms.cpp.i
.PHONY : src/string_transforms.cpp.i

src/string_transforms.s: src/string_transforms.cpp.s
.PHONY : src/string_transforms.s

# target to generate assembly for a file
src/string_transforms.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/perseus.dir/build.make CMakeFiles/perseus.dir/src/string_transforms.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/string_transforms.cpp.s
.PHONY : src/string_transforms.cpp.s

tests/test_all.o: tests/test_all.cpp.o
.PHONY : tests/test_all.o

# target to build an object file
tests/test_all.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/test_all.cpp.o
.PHONY : tests/test_all.cpp.o

tests/test_all.i: tests/test_all.cpp.i
.PHONY : tests/test_all.i

# target to preprocess a source file
tests/test_all.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/test_all.cpp.i
.PHONY : tests/test_all.cpp.i

tests/test_all.s: tests/test_all.cpp.s
.PHONY : tests/test_all.s

# target to generate assembly for a file
tests/test_all.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/test_all.cpp.s
.PHONY : tests/test_all.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... perseus"
	@echo "... tests"
	@echo "... src/geometry.o"
	@echo "... src/geometry.i"
	@echo "... src/geometry.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/move.o"
	@echo "... src/move.i"
	@echo "... src/move.s"
	@echo "... src/move_generation.o"
	@echo "... src/move_generation.i"
	@echo "... src/move_generation.s"
	@echo "... src/network.o"
	@echo "... src/network.i"
	@echo "... src/network.s"
	@echo "... src/square.o"
	@echo "... src/square.i"
	@echo "... src/square.s"
	@echo "... src/state.o"
	@echo "... src/state.i"
	@echo "... src/state.s"
	@echo "... src/string_transforms.o"
	@echo "... src/string_transforms.i"
	@echo "... src/string_transforms.s"
	@echo "... tests/test_all.o"
	@echo "... tests/test_all.i"
	@echo "... tests/test_all.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

